// Legal pages — branded, responsive, dark-mode-friendly starter content served at
// /terms, /privacy, /acceptable-use, /cookies, /disclaimer. Content is a professional
// STARTER draft to remove dead links and set expectations; it must be reviewed by counsel
// before it is relied upon (see the notice banner). No dependencies — pure string HTML.

const BRAND = { amber: "#CF7F18", amber2: "#EE9B2E", ink: "#1F252C", paper: "#F1EEE7" };
const UPDATED = "July 2, 2026";
const CONTACT = { support: "support@bidvoice.ai", privacy: "privacy@bidvoice.ai", legal: "legal@bidvoice.ai" };

// The five pages. Each is a title + ordered sections. Written to be reasonable defaults for
// a US SaaS serving contractors; intentionally conservative and plain-language.
export const LEGAL_SLUGS = ["terms", "privacy", "acceptable-use", "cookies", "disclaimer"];

const P = (s) => s.trim();

const PAGES = {
  terms: {
    title: "Terms of Service",
    intro: "These Terms govern your use of BidVoice, the AI Construction Operating System, and Eden, our AI assistant (together, the “Service”), provided by BidVoice AI (“BidVoice”, “we”, “us”).",
    sections: [
      ["Acceptance", P("By creating an account or using the Service you agree to these Terms. If you use the Service on behalf of a business, you represent that you are authorized to bind that business.")],
      ["Your account", P("You are responsible for the accuracy of your account information, for keeping your credentials secure, and for all activity under your account. You must be at least 18 years old and able to form a binding contract.")],
      ["The Service", P("BidVoice helps contractors capture jobs, draft estimates and proposals, manage projects, and communicate with customers. Eden is an AI assistant; its outputs — including prices, quantities, and drafted text — are suggestions and starting points, not professional advice. You are responsible for reviewing and approving every estimate, price, proposal, and message before it is sent or relied upon.")],
      ["Your content", P("You retain ownership of the content you put into the Service (jobs, customers, photos, pricing, documents). You grant BidVoice a limited license to host and process that content solely to provide the Service to you. You are responsible for having the rights to the content you upload.")],
      ["Payments and subscriptions", P("Paid plans, if any, are billed as described at sign-up. Payment processing may be handled by third parties (e.g., Stripe). Taxes are your responsibility unless stated otherwise. You can cancel at any time; access continues through the end of the paid period unless required otherwise by law.")],
      ["Acceptable use", P("Your use of the Service is also governed by our Acceptable Use Policy. Do not misuse the Service, attempt to break its security, or use it for unlawful purposes.")],
      ["AI outputs and no warranty of accuracy", P("Eden’s pricing and content are generated by AI and may be inaccurate or incomplete. They are placeholders you must set and verify. BidVoice does not guarantee the accuracy of any estimate, quantity, or price. The contractor is solely responsible for the numbers in any bid, proposal, contract, or invoice.")],
      ["Service availability", P("We work to keep the Service available and reliable, but we do not guarantee uninterrupted access. Features may change, and we may perform maintenance that temporarily affects availability.")],
      ["Termination", P("You may stop using the Service at any time. We may suspend or terminate access for violations of these Terms or to comply with law. On termination you may request an export of your data as described in our Privacy Policy.")],
      ["Disclaimers and limitation of liability", P("The Service is provided “as is” and “as available,” without warranties of any kind to the fullest extent permitted by law. To the maximum extent permitted by law, BidVoice’s total liability arising out of or relating to the Service is limited to the amount you paid us in the twelve months before the claim. See also our Disclaimer.")],
      ["Changes to these Terms", P("We may update these Terms. Material changes will be posted here with an updated date. Continued use after changes means you accept the updated Terms.")],
      ["Contact", P(`Questions about these Terms: <a href="mailto:${CONTACT.legal}">${CONTACT.legal}</a>.`)],
    ],
  },
  privacy: {
    title: "Privacy Policy",
    intro: "This Policy explains what information BidVoice collects, how we use it, and the choices you have. We aim to collect only what we need to run the Service for you.",
    sections: [
      ["Information you provide", P("Account details (name, email, company, phone), the business data you enter (jobs, customers, estimates, photos, pricing, documents), and messages you send through the Service.")],
      ["Information collected automatically", P("Basic device and usage information (such as log data and app interactions) needed to operate, secure, and improve the Service. See our Cookie Policy for details on cookies and local storage.")],
      ["How we use information", P("To provide and improve the Service, generate AI assistance through Eden, process payments, send transactional messages (email/SMS you’ve consented to), provide support, keep the Service secure, and comply with law. We do not sell your personal information.")],
      ["Your data stays yours", P("Your business data is scoped to your account and is not shared with other contractors. Access is checked on every request. Private fields such as your margin and internal notes are never shown in a client’s view or in a client PDF.")],
      ["AI processing", P("To generate estimates, summaries, and replies, relevant parts of your content may be processed by AI systems, including trusted third-party AI providers, solely to produce your results. We do not use your private business data to advertise to you.")],
      ["Service providers", P("We use vetted providers to run the Service — for example, hosting, email delivery (Resend), payment processing (Stripe), and AI (model providers). They may process data only to perform services for us.")],
      ["Security", P("We use industry-standard measures including encryption in transit (HTTPS/TLS), hashed passwords, per-account isolation, and signed, expiring links for private files. No system is perfectly secure, but protecting your data is a priority.")],
      ["Data retention", P("We keep your data while your account is active and as needed to provide the Service and meet legal obligations. You can request deletion or export at any time.")],
      ["Your choices and rights", P(`You can access, correct, export, or delete your data, and opt out of non-essential messages. To make a request, contact <a href="mailto:${CONTACT.privacy}">${CONTACT.privacy}</a>. Depending on where you live, you may have additional rights under laws such as the CCPA/CPRA or GDPR.`)],
      ["Text messages (SMS)", P("If you provide a mobile number, we may send transactional and account-related texts. Message and data rates may apply. Reply STOP to unsubscribe or HELP for help. Marketing texts, if ever offered, require separate consent.")],
      ["Children", P("The Service is for business use by adults and is not directed to children under 18.")],
      ["Changes", P("We may update this Policy; material changes will be posted here with a new date.")],
      ["Contact", P(`Privacy questions or requests: <a href="mailto:${CONTACT.privacy}">${CONTACT.privacy}</a>.`)],
    ],
  },
  "acceptable-use": {
    title: "Acceptable Use Policy",
    intro: "To keep BidVoice safe and reliable for every contractor, you agree not to misuse the Service. This Policy is part of our Terms of Service.",
    sections: [
      ["Prohibited conduct", P("Don’t use the Service to break the law, infringe others’ rights, send spam or unlawful messages, upload malware, harass anyone, or misrepresent who you are.")],
      ["Security", P("Don’t attempt to access accounts or data that aren’t yours, probe or breach security or authentication, disrupt the Service, or scrape it in ways that harm performance.")],
      ["Content", P("Don’t upload content you don’t have the rights to, or content that is illegal, deceptive, or harmful. You’re responsible for the accuracy of prices and proposals you send to your customers.")],
      ["Communications", P("Only send messages (email/SMS) to people who expect to hear from you and have provided any required consent. Honor opt-out requests promptly.")],
      ["Fair use of AI", P("Eden is provided to help you run your business. Don’t use it to generate unlawful, deceptive, or abusive content, or to attempt to reverse-engineer the underlying models.")],
      ["Enforcement", P("We may investigate suspected violations and suspend or terminate access as needed to protect the Service and its users.")],
      ["Contact", P(`Report abuse or ask a question: <a href="mailto:${CONTACT.support}">${CONTACT.support}</a>.`)],
    ],
  },
  cookies: {
    title: "Cookie Policy",
    intro: "This Policy explains how BidVoice uses cookies and similar technologies such as browser local storage.",
    sections: [
      ["What we use", P("We use a small amount of local storage and, where applicable, cookies that are strictly necessary to run the app — for example to keep you signed in, remember your language, and make the app work offline as a Progressive Web App.")],
      ["Analytics", P("We may use limited, privacy-respecting analytics to understand how the Service is used so we can improve it. We aim to minimize what we collect.")],
      ["No advertising cookies", P("We do not use third-party advertising cookies to track you across other websites.")],
      ["Your choices", P("You can clear local storage and cookies in your browser settings. Note that clearing strictly-necessary storage may sign you out or reset preferences.")],
      ["Contact", P(`Questions: <a href="mailto:${CONTACT.privacy}">${CONTACT.privacy}</a>.`)],
    ],
  },
  disclaimer: {
    title: "Disclaimer",
    intro: "Please read this Disclaimer carefully. It explains the limits of what BidVoice and Eden provide.",
    sections: [
      ["Not professional advice", P("BidVoice and Eden provide software tools and AI-generated suggestions. They do not provide legal, financial, tax, engineering, or professional construction advice. Consult a qualified professional where appropriate.")],
      ["AI prices are placeholders", P("All AI-generated prices, quantities, unit assumptions, and drafted text are starting points only. The contractor is solely responsible for setting, verifying, and standing behind the real numbers in any estimate, proposal, contract, or invoice.")],
      ["No guarantee of outcomes", P("We don’t guarantee that using the Service will win jobs, increase revenue, or produce accurate estimates. Results depend on your inputs and judgment.")],
      ["Third-party services", P("The Service may link to or integrate with third parties (e.g., payments, accounting, mapping). We’re not responsible for their content, accuracy, or practices.")],
      ["Contact", P(`Questions: <a href="mailto:${CONTACT.legal}">${CONTACT.legal}</a>.`)],
    ],
  },
};

function navLinks(active) {
  const items = [
    ["/terms", "Terms"], ["/privacy", "Privacy"], ["/acceptable-use", "Acceptable Use"],
    ["/cookies", "Cookies"], ["/disclaimer", "Disclaimer"],
  ];
  return items.map(([href, label]) =>
    `<a href="${href}"${href === "/" + active ? ' aria-current="page"' : ""}>${label}</a>`).join("");
}

export function renderLegalPage(slug) {
  const page = PAGES[slug];
  if (!page) return null;
  const body = page.sections.map(([h, txt]) => `<section><h2>${h}</h2><p>${txt}</p></section>`).join("\n");
  return `<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${page.title} · BidVoice</title>
<meta name="robots" content="index,follow">
<link rel="icon" type="image/png" href="/brand-orange.png?v=4">
<meta name="theme-color" content="${BRAND.amber}">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@700;800;900&family=IBM+Plex+Sans:wght@400;500;600&display=swap" rel="stylesheet">
<style>
  :root{color-scheme:light dark;--amber:${BRAND.amber};--amber2:${BRAND.amber2};--ink:${BRAND.ink};--paper:${BRAND.paper};--card:#fff;--tx:#1F252C;--mut:#5c6270;--rule:#e6e0d4}
  @media (prefers-color-scheme:dark){:root{--paper:#0f141b;--card:#161c25;--tx:#eef2f7;--mut:#9aa4b2;--rule:#242c38}}
  *{box-sizing:border-box}
  body{margin:0;background:var(--paper);color:var(--tx);font-family:"IBM Plex Sans",system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;line-height:1.6;-webkit-font-smoothing:antialiased}
  a{color:var(--amber);text-decoration:none}a:hover{text-decoration:underline}
  .wrap{max-width:760px;margin:0 auto;padding:0 22px}
  header{border-bottom:1px solid var(--rule);background:var(--card)}
  .brand{display:flex;align-items:center;gap:10px;padding:16px 0;font-family:"Archivo";font-weight:800;font-size:1.2rem}
  .brand img{width:26px;height:26px;object-fit:contain}
  .brand .v{color:var(--amber)}
  .lnav{display:flex;flex-wrap:wrap;gap:14px;padding:0 0 14px;font-size:.9rem}
  .lnav a{color:var(--mut);font-weight:600}.lnav a[aria-current]{color:var(--amber)}
  main{padding:34px 0 10px}
  h1{font-family:"Archivo";font-weight:900;font-size:2rem;letter-spacing:-.02em;margin:0 0 6px}
  .updated{color:var(--mut);font-size:.9rem;margin:0 0 20px}
  .notice{background:rgba(207,127,24,.10);border:1px solid rgba(207,127,24,.3);border-radius:12px;padding:12px 15px;font-size:.9rem;margin:0 0 26px}
  h2{font-family:"Archivo";font-weight:800;font-size:1.15rem;margin:26px 0 6px}
  .intro{font-size:1.05rem;color:var(--tx)}
  .trust{display:flex;flex-wrap:wrap;gap:10px 18px;margin:26px 0 4px;padding:16px 0;border-top:1px solid var(--rule);border-bottom:1px solid var(--rule);font-size:.86rem;color:var(--mut)}
  .trust b{color:var(--tx)}
  footer{border-top:1px solid var(--rule);margin-top:30px;padding:22px 0 40px;color:var(--mut);font-size:.88rem;background:var(--card)}
  footer a{color:var(--mut);font-weight:600}
  .fnav{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:8px}
</style></head>
<body>
<header><div class="wrap">
  <a class="brand" href="/"><img src="/brand-orange.png?v=4" alt=""><span>Bid<span class="v">Voice</span></span></a>
  <nav class="lnav">${navLinks(slug)}</nav>
</div></header>
<main><div class="wrap">
  <h1>${page.title}</h1>
  <p class="updated">Last updated: ${UPDATED}</p>
  <div class="notice"><b>Starter document.</b> This is a good-faith draft to explain how BidVoice works. It has not yet been reviewed by legal counsel and does not constitute legal advice. It will be updated before and as we scale.</div>
  <p class="intro">${page.intro}</p>
  ${body}
  <div class="trust">
    <span>🔒 <b>SSL secured</b></span>
    <span>🛡️ <b>Encrypted in transit</b> (TLS)</span>
    <span>👤 <b>Your data stays private</b></span>
    <span>⚡ <b>AI-powered</b> by Eden</span>
  </div>
</div></main>
<footer><div class="wrap">
  <nav class="fnav">
    <a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a>
    <a href="mailto:${CONTACT.support}">Contact</a><a href="mailto:${CONTACT.support}">Support</a>
  </nav>
  <div>© BidVoice AI · Your AI employee for contractors.</div>
</div></footer>
</body></html>`;
}
